 
package com.mycompany.sample_db_conc;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

public class DBFrame extends javax.swing.JFrame {

    Connection con;
    String id = null; 
    String name = null; 
    String phone = null;
    
    public DBFrame() {
        initComponents();
        view();
    }
    public void view(){
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/testDemo","root","");
            PreparedStatement pre=con.prepareStatement("select * from student");
            ResultSet res=pre.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)StudentTable_jTable.getModel();
            tm.setRowCount(0);
            
            while(res.next())
            {
                Object o[]={res.getInt("ID"), res.getString("Name"), res.getDouble("Phn_no")};
                tm.addRow(o);
            }
        }
        catch(Exception e){
             System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heading_JLabel = new javax.swing.JLabel();
        Insert_JButton = new javax.swing.JButton();
        Delete_JButton = new javax.swing.JButton();
        Update_JButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable_jTable = new javax.swing.JTable();
        Phone_jTextFiel = new javax.swing.JTextField();
        ID_jTextField = new javax.swing.JTextField();
        Name_jTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Heading_JLabel.setBackground(new java.awt.Color(255, 255, 255));
        Heading_JLabel.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
        Heading_JLabel.setForeground(new java.awt.Color(98, 98, 98));
        Heading_JLabel.setText("Student Details");

        Insert_JButton.setText("Insert  ");
        Insert_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_JButtonActionPerformed(evt);
            }
        });

        Delete_JButton.setText("Delete ");
        Delete_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_JButtonActionPerformed(evt);
            }
        });

        Update_JButton.setText("Update");
        Update_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_JButtonActionPerformed(evt);
            }
        });

        StudentTable_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "uid", "uname", "uphn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        StudentTable_jTable.setRowHeight(18);
        jScrollPane1.setViewportView(StudentTable_jTable);

        Phone_jTextFiel.setText("Enter Phn No");
        Phone_jTextFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phone_jTextFielActionPerformed(evt);
            }
        });

        ID_jTextField.setText("Enter ID");
        ID_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_jTextFieldActionPerformed(evt);
            }
        });

        Name_jTextField.setText("Enter Name");
        Name_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_jTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phone_jTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Insert_JButton)
                    .addComponent(Update_JButton)
                    .addComponent(Delete_JButton))
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Heading_JLabel)
                .addGap(345, 345, 345))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Heading_JLabel)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ID_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(Name_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(Phone_jTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Insert_JButton)
                        .addGap(49, 49, 49)
                        .addComponent(Update_JButton)
                        .addGap(50, 50, 50)
                        .addComponent(Delete_JButton)
                        .addGap(25, 25, 25)))
                .addGap(0, 121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Delete
    private void Delete_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_JButtonActionPerformed
        
        id = ID_jTextField.getText();
        name = Name_jTextField.getText();
        phone = Phone_jTextFiel.getText();
        
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/testDemo","root","");
            System.out.println("success");
            
            // Query
            String sql = "DELETE FROM student WHERE ID=?";
 
            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, id);
 
            int rowsDeleted = statement.executeUpdate();
            if (rowsDeleted > 0) {
                System.out.println("A user was deleted successfully!");
            }
            
            // call view method to show table
            view();
        }
        
        catch(Exception e){
           System.out.println(e);
        }                                              
    }//GEN-LAST:event_Delete_JButtonActionPerformed

    // Insert
    private void Insert_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_JButtonActionPerformed
       
        id = ID_jTextField.getText();
        name = Name_jTextField.getText();
        phone = Phone_jTextFiel.getText();
        
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/testDemo","root","");
            System.out.println("success");
            
            // Query
            String sql = "INSERT INTO student (ID, Name, Phn_no) VALUES (?, ?, ?)";
 
            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, id);
            statement.setString(2, name);
            statement.setString(3, phone);
 
            int rowsInserted = statement.executeUpdate();
            if (rowsInserted > 0) {
                System.out.println("A new user was inserted successfully!");
            }
            
            // call view method to show table
            view();
        }
        catch(Exception e){
           System.out.println(e);
        }
    }//GEN-LAST:event_Insert_JButtonActionPerformed

    // Update
    private void Update_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_JButtonActionPerformed
        
        id = ID_jTextField.getText();
        name = Name_jTextField.getText();
        phone = Phone_jTextFiel.getText();
        
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/testDemo","root","");
            System.out.println("success");
            
            // Query
            String sql = "UPDATE student SET Name=?, Phn_no=? WHERE ID=?";
            
            PreparedStatement statement = con.prepareStatement(sql);
            
            statement.setString(1, name);
            statement.setString(2, phone);
            statement.setString(3, id);
            
            int rowsUpdated = statement.executeUpdate();
            if (rowsUpdated > 0) {
                System.out.println("An existing user was updated successfully!");
            } 
            
            // call view method to show table
            view();
        }
        catch(Exception e){
           System.out.println(e);
        }
    }//GEN-LAST:event_Update_JButtonActionPerformed

    private void ID_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_jTextFieldActionPerformed

    private void Phone_jTextFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone_jTextFielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone_jTextFielActionPerformed

    private void Name_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_jTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
                
        try {
            // Database intialization
            Class.forName("com.mysql.cj.jdbc.Driver");
           
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch(Exception e){
           System.out.println(e);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_JButton;
    private javax.swing.JLabel Heading_JLabel;
    private javax.swing.JTextField ID_jTextField;
    private javax.swing.JButton Insert_JButton;
    private javax.swing.JTextField Name_jTextField;
    private javax.swing.JTextField Phone_jTextFiel;
    private javax.swing.JTable StudentTable_jTable;
    private javax.swing.JButton Update_JButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
